import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormFields, Loader } from '../components'

const CreatePost = () => {

  const navigate = useNavigate()

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: ''
  })

  const [generatingImg, setGeneratingImg] = useState(false)

  const handleSubmit = () => {

  }
  const handleChange = (e) => {

  }

  const handleSurpriseMe = () => {

  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
          Create imaginative and visually stunning
          image generated by DALL-E AI
        </p>
      </div>
      <form className='mt-16 mx-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormFields
            LabelName="Your Name"
            type="text"
            name="name"
            placeholder="Ai net"
            value={form.name}
            handleChange={handleChange}
          />
          <FormFields
            LabelName="Prompt"
            type="text"
            name="prompt"
            placeholder='an oil pastel drawing of an annoyed cat in a spaceship'
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
          <div className='relative bg-gray-50 border border-gray-300
          text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>

          </div>
        </div>
      </form>
    </section>
  )
}

export default CreatePost